### ISSUE TITLE
Problema de permisos y ejecución en Jupyter Lab con Docker Compose

### ISSUE THREAD

**Issue by CanaletaFast** [heirinsinho/all-in-one-docker-bigdataops#1]
Al intentar ejecutar Jupyter Lab en el contenedor Docker, surgió un problema relacionado con permisos en el directorio /home/jovyan/.local/share/jupyter. Esto provocaba errores en la ejecución. 

El archivo actualizado docker-compose.yaml es:

jupyter:
  platform: linux/amd64
  image: base-jupyter:latest
  container_name: jupyter
  ports:
    - "8890:8888"
    - "4040:4040"
  environment:
    - JUPYTER_ENABLE_LAB=yes
  depends_on:
    - spark-master
    - spark-history-server
  volumes:
    - ./jupyter/notebooks:/home/jovyan
  entrypoint: []
  user: "1000:1000"
  command: bash -c "chmod -R 700 /home/jovyan/.local/share/jupyter && exec jupyter lab --NotebookApp.token=''"

Las correcciones:   
- Se agrega el campo user para especificar el usuario y evitar problemas de permisos.
- Se modifica el command para ajustar los permisos antes de ejecutar Jupyter Lab.
- Se agrega un entrypoint vacío para evitar conflictos con los comandos predefinidos.

**Comment by heirinsinho** [comment]
Gracias!
